### ISSUE TITLE
How may I actively contribute to this project?

### ISSUE THREAD

**Issue by serhack** [OWASP/Blockchain-Security-Framework#5]
Hello,
I'm SerHack, a security engineer, developer, writer and a Monero contributor. I'd like to write about security and blockchain in order to improve the environment (sometimes too toxic). The main question is: how may I contribute to this project?

I've not seen any commits for months and I was wondering if the project was dead. I think some points of your lists can not be applicable / out of scope for blockchain.

**Comment by deepakrpandey** [comment]
Hi,

Please share your email address and I will get in touch with you soon. 

We are currently working on slack and have prepared some material which we are reviewing internally before we put it over our git repo. 

Could you please elaborate on the points that you deem not applicable and reasons for them, if any. Also, feel free to add what is missing in our list. 

I will discuss the same with the team as well and improve on those.

**Comment by serhack** [comment]
hi at serhack dot me is my email. I'd like to contribute a project with more transparency. If I can ask, why are you currently working only on slack?

**Comment by deepakrpandey** [comment]
Because slack is what we do behind the scenes and github repo will be what we deliver - that's how the team had planned it out. 

I have sent you an email.
